/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fabian
 */
public class MenuHeladeria extends javax.swing.JFrame {

    /**
     * Creates new form MenuHeladeria
     */
    public MenuHeladeria() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guiChocolate = new javax.swing.JButton();
        guiGalleta = new javax.swing.JButton();
        guiNeonEspecial = new javax.swing.JButton();
        guiFresa = new javax.swing.JButton();
        guiVainilla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        guiprecioChocolate = new javax.swing.JLabel();
        guiPrecioFresa = new javax.swing.JLabel();
        guiPrecioGalleta = new javax.swing.JLabel();
        guiPrecioNeonEspecial = new javax.swing.JLabel();
        guiPrecioVainilla = new javax.swing.JLabel();
        guiPuntos2 = new javax.swing.JLabel();
        guiPuntos3 = new javax.swing.JLabel();
        guiPuntos1 = new javax.swing.JLabel();
        guiPuntos5 = new javax.swing.JLabel();
        guiPuntos4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (2).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("jCheckBox1");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (3).png")); // NOI18N

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (3).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image(0).png")); // NOI18N
        jLabel1.setText("jLabel1");

        guiChocolate.setBackground(new java.awt.Color(0, 0, 0));
        guiChocolate.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (2).png")); // NOI18N
        guiChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiChocolateActionPerformed(evt);
            }
        });

        guiGalleta.setBackground(new java.awt.Color(0, 0, 0));
        guiGalleta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (4).png")); // NOI18N
        guiGalleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiGalletaActionPerformed(evt);
            }
        });

        guiNeonEspecial.setBackground(new java.awt.Color(0, 0, 0));
        guiNeonEspecial.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (5).png")); // NOI18N
        guiNeonEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiNeonEspecialActionPerformed(evt);
            }
        });

        guiFresa.setBackground(new java.awt.Color(0, 0, 0));
        guiFresa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-image (3).png")); // NOI18N
        guiFresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiFresaActionPerformed(evt);
            }
        });

        guiVainilla.setBackground(new java.awt.Color(0, 0, 0));
        guiVainilla.setForeground(new java.awt.Color(0, 0, 0));
        guiVainilla.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-imageV.png")); // NOI18N
        guiVainilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiVainillaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabian\\Desktop\\PROYECTO CS\\MicrosoftTeams-imageME.png")); // NOI18N
        jLabel3.setText("jLabel3");

        guiprecioChocolate.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        guiprecioChocolate.setText("¢1100");

        guiPrecioFresa.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        guiPrecioFresa.setText("¢1000");

        guiPrecioGalleta.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        guiPrecioGalleta.setText("¢1200");

        guiPrecioNeonEspecial.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        guiPrecioNeonEspecial.setText("¢1500");

        guiPrecioVainilla.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        guiPrecioVainilla.setText("   ¢900");

        guiPuntos2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        guiPuntos2.setText("----------------------");

        guiPuntos3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        guiPuntos3.setText("----------------------");

        guiPuntos1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        guiPuntos1.setText("----------------------");

        guiPuntos5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        guiPuntos5.setText("----------------------");

        guiPuntos4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        guiPuntos4.setText("----------------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guiVainilla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiChocolate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiFresa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiGalleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guiNeonEspecial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guiPuntos2)
                            .addComponent(guiPuntos3)
                            .addComponent(guiPuntos5)
                            .addComponent(guiPuntos4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guiprecioChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiPrecioFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiPrecioGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guiPrecioNeonEspecial)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guiPuntos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guiPrecioVainilla)
                        .addGap(93, 93, 93))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiVainilla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guiPrecioVainilla)
                        .addComponent(guiPuntos1)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiChocolate)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guiprecioChocolate)
                        .addComponent(guiPuntos2)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guiPrecioFresa)
                        .addComponent(guiPuntos3)))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guiGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guiNeonEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(guiPrecioNeonEspecial)
                                .addComponent(guiPuntos5))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guiPrecioGalleta)
                        .addComponent(guiPuntos4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean vainilla = guiVainilla.isSelected();
        boolean chocolate = guiChocolate.isSelected();
        boolean fresa = guiFresa.isSelected();
        boolean galleta = guiGalleta.isSelected();
        boolean neon = guiNeonEspecial.isSelected();
        
        System.out.println("Helado Vainilla:" + vainilla);
        System.out.println("Helado Chocolate:" + chocolate);
        System.out.println("Helado Fresa:" + fresa);
        System.out.println("Helado Galleta:" + galleta);
        System.out.println("Helado Neon Especial:" + neon);

        new Factura(vainilla, chocolate, fresa, galleta, neon).setVisible(true);
        

        guiVainilla.setSelected(false);
        guiChocolate.setSelected(false);
        guiFresa.setSelected(false);
        guiGalleta.setSelected(false);
        guiNeonEspecial.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guiVainillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiVainillaActionPerformed
        // TODO add your handling code here:
        boolean vainilla = guiVainilla.isSelected();
        System.out.println("Helado Vainilla:" + vainilla);
        guiVainilla.setSelected(false);
    }//GEN-LAST:event_guiVainillaActionPerformed

    private void guiChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiChocolateActionPerformed
        // TODO add your handling code here:
        boolean chocolate = guiChocolate.isSelected();
        System.out.println("Helado Chocolate:" + chocolate);
        guiChocolate.setSelected(false);
    }//GEN-LAST:event_guiChocolateActionPerformed

    private void guiFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiFresaActionPerformed
        // TODO add your handling code here:
        boolean fresa = guiFresa.isSelected();
        System.out.println("Helado Fresa:" + fresa);
        guiFresa.setSelected(false);
    }//GEN-LAST:event_guiFresaActionPerformed

    private void guiGalletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiGalletaActionPerformed
        // TODO add your handling code here:
        boolean galleta = guiGalleta.isSelected();
        System.out.println("Helado Galleta:" + galleta);
        guiGalleta.setSelected(false);
    }//GEN-LAST:event_guiGalletaActionPerformed

    private void guiNeonEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiNeonEspecialActionPerformed
        // TODO add your handling code here:
        boolean neon = guiNeonEspecial.isSelected();
        System.out.println("Helado Neon Especial:" + neon);
        guiNeonEspecial.setSelected(false);
    }//GEN-LAST:event_guiNeonEspecialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHeladeria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiChocolate;
    private javax.swing.JButton guiFresa;
    private javax.swing.JButton guiGalleta;
    private javax.swing.JButton guiNeonEspecial;
    private javax.swing.JLabel guiPrecioFresa;
    private javax.swing.JLabel guiPrecioGalleta;
    private javax.swing.JLabel guiPrecioNeonEspecial;
    private javax.swing.JLabel guiPrecioVainilla;
    private javax.swing.JLabel guiPuntos1;
    private javax.swing.JLabel guiPuntos2;
    private javax.swing.JLabel guiPuntos3;
    private javax.swing.JLabel guiPuntos4;
    private javax.swing.JLabel guiPuntos5;
    private javax.swing.JButton guiVainilla;
    private javax.swing.JLabel guiprecioChocolate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
